sudo systemctl disable swar-watch
sudo systemctl disable swar-watch.service
sudo systemctl disable swar-watch.timer
sudo systemctl disable harvester-watch
sudo systemctl disable harvester-watch.service
sudo systemctl disable harvester-watch.timer
sudo systemctl stop swar-watch
sudo systemctl stop swar-watch.service
sudo systemctl stop swar-watch.timer
sudo systemctl stop harvester-watch
sudo systemctl stop harvester-watch.service
sudo systemctl stop harvester-watch.timer
